[[redirects]]
  from = "/media/*"
  to = "https://storage.googleapis.com/REACT_APP_BUCKET/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/projects"
  to = "REACT_APP_JSON_BIN_PROJECTS"
  status = 200
  force = true
  headers = {
    X-Access-Key = "REACT_APP_JSON_BIN_KEY"
    Content-Type = "application/json"
  }

[[redirects]]
  from = "/api/resume"
  to = "REACT_APP_JSON_BIN_RESUME"
  status = 200
  force = true
  headers = {
    X-Access-Key = "REACT_APP_JSON_BIN_KEY"
    Content-Type = "application/json"
  }
