[[redirects]]
    from="/api/projects/*"
    to="$REACT_APP_JSON_BIN_PROJECTS/:splat"
    [redirects.headers]
        X-Access-Key="$REACT_APP_JSON_BIN_KEY"
        Content-Type=application/json

[[redirects]]
    from="/api/resume/*"
    to="$REACT_APP_JSON_BIN_RESUME/:splat"
    [redirects.headers]
        X-Access-Key="$REACT_APP_JSON_BIN_KEY"
        Content-Type=application/json
